%% loop_test_vidDeconvConfig %%
% A loop file to run the unit tests for checking the modularity of the
% toolbox

clear; clc;

% Define paths
options.vidDataRoot = './data/neural/'; % update with actual path if needed
options.bhvDataRoot = './data/behav/';
options.neuralDataRoot = './data/neural/';
options.bhvFileExtension = '_behav_probability_sessions.csv';
options.neuralFileExtension = '_fluor_timeseries_probability_sessions.csv';

addpath(genpath('./utils'));
addpath(genpath('./external'));
addpath(genpath('./main'));
addpath(genpath('./data'));

options.variableDefs = struct( ...
  'stimulus', struct( ...
      'type', 'event', ...
      'timeRef', 'stimulusOnsetTime', ...
      'vars', {{ ...
          'stimContrast0', 'stimContrastR00625', 'stimContrastL00625', ...
          'stimContrastR0125', 'stimContrastL0125', ...
          'stimContrastR025', 'stimContrastL025', ...
          'stimContrastR05', 'stimContrastL05', ...
          'stimContrastR1', 'stimContrastL1' ...
      }} ...
  ), ...
  'reward', struct( ...
      'type', 'event', ...
      'timeRef', 'outcomeTime', ...
      'vars', {{ ...
          'rewardR0', 'rewardL0', ...
          'rewardR00625', 'rewardL00625', ...
          'rewardR0125', 'rewardL0125', ...
          'rewardR025', 'rewardL025', ...
          'rewardR05', 'rewardL05', ...
          'rewardR1', 'rewardL1'...
      }} ...
  ), ...
  'choice', struct( ...
      'type', 'event', ...
      'timeRef', 'choiceStartTime', ...
      'vars', {{'choiceR', 'choiceL'}} ...
  ), ...
  'neural', struct( ...
      'type', 'neural', ...
      'timeRef', {{'LeftDLS_DA', 'RightDLS_ACH'}} ...
  ), ...
  'vid', struct( ...
      'type', 'continuous', ...
      'timeRef', {{'eventTimes'}}, ...
      'vars', {{'MovementPC', 'MotionPC'}} ...
  ), ...
   'keypoint', struct( ...
      'type', 'continuous', ...
      'timeRef', {{'eventTimes'}}, ...
      'vars', {{'mouth_x', 'mouth_y', 'lowerlip_x', 'lowerlip_y'}} ...
  ), ...
   'vidAvg', struct( ...
      'type', 'trial', ...
      'timeRef', {{'NaN'}}, ...
      'vars', {{'MovementPC', 'MotionPC'}} ...
  ), ... 
  'choiceHistorytAvg', struct( ...
      'type', 'trial', ...
      'timeRef', {{'NaN'}}, ...
      'vars', {{'choiceHistory'}} ...
  ) ...
);

%%% --- ENTER YOUR PATHS HERE ---
% This is where we are now (where the code is to be found):
options.codeDir = fileparts(mfilename('fullpath'));

% This is the base root for both raw data and analysis:
options.mainDir = '/Users/heiwinglau/Documents/Research/DPhil/rotation/lak/'; % please change
options.rawDir = fullfile(options.mainDir, 'data'); % please change
options.workDir = fullfile(options.mainDir, 'analysis'); % please change

% Optional steps - plotting design matrix for each regressor group
options.plotDesignMatrix = false;

options.sRate = 20;  % Hz
options.preTime = 0.5; % time before the onset of an event that is included in the time kernel
options.postTime = 2; % time after the onset of an event that is included in the time kernel

% Define subjects and sessions
mouseList = {'MFE008'};
sessionList = {'2022-09-13_1'};

% Initialise main object to store data
obj = struct();

for i = 1:length(mouseList)
    mouse = mouseList{i};
    session = sessionList{i};
    expRef = strcat(session, '_', mouse);
    
    %% === Video / Facemap Data ===
    tmp = load('./data/vid/vidData'); % make sure we are in the /test/ file while running unit tests
    sessionField = matlab.lang.makeValidName(['session_' expRef]);
    obj.vid = tmp.vidData.(mouse).(sessionField); 

    %% === Behavioural / Neural Data ===
    vidDeconv_loadBhvNeuralData; % This is in the examples/ folder

end

import matlab.unittest.TestSuite
import matlab.unittest.TestRunner

% Create a suite from your test class
suite = TestSuite.fromClass(?test_vidDeconvConfig);

% Make a runner that prints to the command window
runner = TestRunner.withTextOutput('Verbosity', 3);

% Run the suite
results = runner.run(suite);

% Show table of results
disp(table({results.Name}', [results.Passed]'))
