function options = cingulateDMS_options
    % *LEMGrin_options*: Sets all options for the analysis of neuromodulators (DA/ ACh)
    % from the instrumental task in the vidDeconv (video deconvolution) study.
    % 
    % OUT:
    % options - the struct that holds all analysis options

%%%% --- General Set-Up ---
addpath(genpath('../utils'));
addpath(genpath('../external'));
addpath(genpath('../main'));
addpath(genpath('../data'));
addpath(genpath('../exampleData'));
addpath(genpath('../examples'));

%%% --- ENTER YOUR PATHS HERE ---
% Get the current directory and add all subfolders
addpath(genpath(pwd)); % You should be at the root of your code directory

% Set data root paths relative to the current directory
options.bhvDataRoot    = '//qnap-al001.dpag.ox.ac.uk/STan/Data/cingulateDMS_output/analysis/';
options.neuralDataRoot = '//qnap-al001.dpag.ox.ac.uk/STan/Data/cingulateDMS_output/analysis/';
options.rawDataRoot    = '//qnap-al001.dpag.ox.ac.uk/Data/';
options.vidDataRoot    = '/Volumes/Data'; % macOS config

% Data file name definition
options.bhvFileExtension = '_CorrectedeventTimes_withLicks.csv'; % please change
options.neuralFileExtension = '_flu_detrend_z_scored.csv'; % please change
options.lickTraceFileExtension = '*_licksbinned.csv';
options.neuralDataTimestampExtension = '*_imaging_frames.txt';

% Optional steps - plotting design matrix for each regressor group
options.plotDesignMatrix = false;

%%%--- expRef IDs -------------------------------------------------%%%
options.expRef = {'2025-09-16_1_SAT035'}; %{'2024-04-23_1_MAT008'}; %

%-- beta kernel config --------------------------------------------------%
options.sRate = 15;  % Hz
options.preTime = 0.5; % time before the onset of an event that is included in the time kernel
options.postTime = 2; % time after the onset of an event that is included in the time kernel

% For the following, please make sure there is no NaN events as it is
% important for trial boundary definitions down the line
options.firstTrialEvent = 'stimulusOnsetTime'; % First event that happen in each trial (assuming it stays the same for every trial)
options.lastTrialEvent = 'rewardTime'; % Last event that happen in each trial (assuming it stays the same for every trial)

%-- Linear Encoding Model Variable Definitions --------------------------------------------------%
options.variableDefs = struct( ...
  'stimulus', struct( ...
      'type', 'event', ...
      'timeRef', 'stimulusOnsetTime', ...
      'vars', {{'^stim.*0$'}}, ... % '100% Rewarded' will get changed to stim100
      'betaPreTime', 0, ...
      'betaPostTime', 2 ...
  ), ...
  'reward', struct( ...
      'type', 'event', ...
      'timeRef', 'rewardTime', ...
      'vars', {{'rewarded', 'unrewarded'}}, ...
      'betaPreTime', 0.5, ...
      'betaPostTime', 2 ...
  ), ...
  'choice', struct( ...
      'type', 'event', ...
      'timeRef', 'choiceStartTime', ...
      'vars', {{'choiceR', 'choiceL'}}, ...
      'betaPreTime', 0.5, ...
      'betaPostTime', 1 ...
  ), ...
  'stimulusXprelick', struct( ...
      'type', 'event', ...
      'timeRef', 'stimulusOnsetTime', ...
      'vars', {{'^stim.*_.*licked'}}, ... %e.g. stim100_prelicked or stim100_nonlicked
      'betaPreTime', 0, ...
      'betaPostTime', 2 ...
  ), ...
  'stimulusXreward', struct( ...
      'type', 'event', ...
      'timeRef', 'rewardTime', ...
      'vars', {{'^stim.*_.*rewarded'}}, ... %e.g. stim100_rewarded or stim100_unrewarded
      'betaPreTime', 0.5, ...
      'betaPostTime', 2 ...
  ), ...
  'prelick', struct( ...
      'type', 'trial', ...
      'timeRef', {{'NaN'}}, ...
      'vars', {{'prelick'}} ...
  ), ...
  'lickTrace', struct( ...
      'type', 'continuous', ...
      'fileExtension', options.lickTraceFileExtension, ...
      'timeRef', {{'eventTimes'}}, ...
      'vars', {{'lickTrace'}} ...
  ), ...
  'neural', struct( ...
      'type', 'neural', ...
      'timeRef', 'time', ...
      'vars', {{'cell.*'}} ...
  ) ...
);

% 'prev1_stimulus', struct( ...
  %     'type', 'trial', ...
  %     'timeRef', {{'NaN'}}, ...
  %     'vars', {{'%_prev1'}} ... %e.g. 100%_prev1
  % ), ...
% 'prevOutcome', struct( ...
%       'type', 'trial', ...
%       'timeRef', {{'NaN'}}, ...
%       'vars', {{'prevOutcome'}} ...
%   ), ...

end